$INCLUDE "bl_config.inc"

.SECTION .branch_table, AT USER_BRANCH_TABLE
    BR      !!_start                        ;   Entry                               0x0000
    BR      !!_r_default_interrupt_handler  ;   OCD                                 0x0002
    BR      !!_r_default_interrupt_handler  ;   INTWDTI                             0x0004
    BR      !!_r_lvd_interrupt              ;   INTLVI                              0x0006
    BR      !!_r_default_interrupt_handler  ;   INTP0                               0x0008
    BR      !!_r_intc1_interrupt            ;   INTP1                               0x000A
    BR      !!_r_default_interrupt_handler  ;   INTP2                               0x000C
    BR      !!_r_intc3_interrupt            ;   INTP3                               0x000E
    BR      !!_r_default_interrupt_handler  ;   INTP4                               0x0010
    BR      !!_r_default_interrupt_handler  ;   INTP5                               0x0012
    BR      !!_r_uart2_interrupt_send       ;   INTST2/INTSTMG0                     0x0014
    BR      !!_r_uart2_interrupt_receive    ;   INTSR2/INTSRMG0                     0x0016
    BR      !!_r_default_interrupt_handler  ;   INTSRE2/INTSREMG0                   0x0018
    BR      !!_r_default_interrupt_handler  ;   INTCR/INTSMP00/INTSMP10             0x001A
    BR      !!_r_default_interrupt_handler  ;   INTAES/INTAESF                      0x001C
    BR      !!_r_uart0_interrupt_send       ;   INTCSI00/INTIIC00/INTST0            0x001E
    BR      !!_r_default_interrupt_handler  ;   INTIICA0                            0x0020
    BR      !!_r_uart0_interrupt_receive    ;   INTSR0                              0x0022
    BR      !!_r_default_interrupt_handler  ;   INTSRE0/INTTM01H                    0x0024
    BR      !!_r_default_interrupt_handler  ;   INTCSI10/INTIIC10/INTST1            0x0026
    BR      !!_r_default_interrupt_handler  ;   INTSR1                              0x0028
    BR      !!_r_default_interrupt_handler  ;   INTSRE1/INTTM03H                    0x002A
    BR      !!_r_tau0_channel0_interrupt    ;   INTTM00                             0x002C
    BR      !!_r_rtc_alarm0interrupt        ;   INTRTCALM0/INTSMP01/INTSMP11        0x002E
    BR      !!_r_default_interrupt_handler  ;   INTFM/INTSMP02/INTSMP12             0x0030
    BR      !!_r_default_interrupt_handler  ;   INTTM01                             0x0032
    BR      !!_r_default_interrupt_handler  ;   INTTM02                             0x0034
    BR      !!_r_default_interrupt_handler  ;   INTTM03                             0x0036
    BR      !!_r_default_interrupt_handler  ;   INTAD                               0x0038
    BR      !!_r_rtc_periodicinterrupt      ;   INTRTCPRD/INTSMP03/INTSMP13         0x003A
    BR      !!_r_default_interrupt_handler  ;   INTIT                               0x003C
    BR      !!_r_rtc_alarm1interrupt        ;   INTKR/INTRTCALM1/INTSMP04/INTSMP14  0x003E
    BR      !!_r_csi30_interrupt            ;   INTCSI30/INTIIC30/INTST3            0x0040
    BR      !!_r_default_interrupt_handler  ;   INTSR3                              0x0042
    BR      !!_r_default_interrupt_handler  ;   INTDSAD/INTSMP05/INTSMP15           0x0044
    BR      !!_r_default_interrupt_handler  ;   INTTM04                             0x0046
    BR      !!_r_default_interrupt_handler  ;   INTSMOTA0/INTTM05                   0x0048
    BR      !!_r_default_interrupt_handler  ;   INTP6                               0x004A
    BR      !!_r_default_interrupt_handler  ;   INTP7                               0x004C
    BR      !!_r_intrtcic2_interrupt        ;   INTP12/INTRTCIC2                    0x004E
    BR      !!_r_intrtcic1_interrupt        ;   INTP13/INTRTCIC1                    0x0050
    BR      !!_r_intrtcic0_interrupt        ;   INTP14/INTRTCIC0                    0x0052
    BR      !!_r_default_interrupt_handler  ;   INTSMOTB0/INTTM06                   0x0054
    BR      !!_r_default_interrupt_handler  ;   INTSMOTA1/INTTM07                   0x0056
    BR      !!_r_default_interrupt_handler  ;   INTIT00                             0x0058
    BR      !!_r_default_interrupt_handler  ;   INTIT01                             0x005A
    BR      !!_r_default_interrupt_handler  ;   INTSRE3                             0x005C
    BR      !!_r_default_interrupt_handler  ;   INTMACLOF/INTSMOTB1                 0x005E
    BR      !!_r_default_interrupt_handler  ;   INTOSDC                             0x0060
    BR      !!_r_default_interrupt_handler  ;   INTFL                               0x0062
    BR      !!_r_default_interrupt_handler  ;   INTP8                               0x0064
    BR      !!_r_default_interrupt_handler  ;   INTP9                               0x0066
    BR      !!_r_default_interrupt_handler  ;   INTIT10                             0x0068
    BR      !!_r_default_interrupt_handler  ;   INTIT11                             0x006A
    BR      !!_r_lvd_vddinterrupt           ;   INTIT20/INTLVDVDD                   0x006C
    BR      !!_r_lvd_vbatinterrupt          ;   INTIT21/INTLVDVBAT                  0x006E
    BR      !!_r_lvd_vrtcinterrupt          ;   INTIT30/INTLVDVRTC                  0x0070
    BR      !!_r_lvd_exlvdinterrupt         ;   INTIT31/INTLVDEXLVD                 0x0072
    BR      !!_r_default_interrupt_handler  ;   INTST4/INTSTMG1                     0x0074
    BR      !!_r_default_interrupt_handler  ;   INTSR4/INTSRMG1                     0x0076
    BR      !!_r_default_interrupt_handler  ;   INTSRE4/INTSREMG1                   0x0078
    BR      !!_r_default_interrupt_handler  ;   INTDSADDEC/INTTRJ0                  0x007A
    BR      !!_r_default_interrupt_handler  ;   INTTRJ1                             0x007C
    BR      !!_r_sw_break_interrupt_handler ;   Software break                      0x007E
    