$INCLUDE "bl_config.inc"

.SECTION .branch_table, AT METROLOGY_BRANCH_TABLE
    BR      !!_em_cstart                    ;   Entry                               0x0000
    .DB4    0xffffffff                      ;   OCD                                 0x0002
    .DB4    0xffffffff                      ;   INTWDTI                             0x0004
    .DB4    0xffffffff                      ;   INTLVI                              0x0006
    .DB4    0xffffffff                      ;   INTP0                               0x0008
    .DB4    0xffffffff                      ;   INTP1                               0x000A
    .DB4    0xffffffff                      ;   INTP2                               0x000C
    .DB4    0xffffffff                      ;   INTP3                               0x000E
    .DB4    0xffffffff                      ;   INTP4                               0x0010
    .DB4    0xffffffff                      ;   INTP5                               0x0012
    .DB4    0xffffffff                      ;   INTST2/INTSTMG0                     0x0014
    .DB4    0xffffffff                      ;   INTSR2/INTSRMG0                     0x0016
    .DB4    0xffffffff                      ;   INTSRE2/INTSREMG0                   0x0018
    .DB4    0xffffffff                      ;   INTCR/INTSMP00/INTSMP10             0x001A
    .DB4    0xffffffff                      ;   INTAES/INTAESF                      0x001C
    .DB4    0xffffffff                      ;   INTCSI00/INTIIC00/INTST0            0x001E
    BR      !!_r_iica0_interrupt            ;   INTIICA0                            0x0020
    .DB4    0xffffffff                      ;   INTSR0                              0x0022
    .DB4    0xffffffff                      ;   INTSRE0/INTTM01H                    0x0024
    .DB4    0xffffffff                      ;   INTCSI10/INTIIC10/INTST1            0x0026
    .DB4    0xffffffff                      ;   INTSR1                              0x0028
    .DB4    0xffffffff                      ;   INTSRE1/INTTM03H                    0x002A
    .DB4    0xffffffff                      ;   INTTM00                             0x002C
    .DB4    0xffffffff                      ;   INTRTCALM0/INTSMP01/INTSMP11        0x002E
    .DB4    0xffffffff                      ;   INTFM/INTSMP02/INTSMP12             0x0030
    .DB4    0xffffffff                      ;   INTTM01                             0x0032
    BR      !!_r_tau0_channel2_interrupt    ;   INTTM02                             0x0034
    .DB4    0xffffffff                      ;   INTTM03                             0x0036
    .DB4    0xffffffff                      ;   INTAD                               0x0038
    .DB4    0xffffffff                      ;   INTRTCPRD/INTSMP03/INTSMP13         0x003A
    .DB4    0xffffffff                      ;   INTIT                               0x003C
    .DB4    0xffffffff                      ;   INTKR/INTRTCALM1/INTSMP04/INTSMP14  0x003E
    .DB4    0xffffffff                      ;   INTCSI30/INTIIC30/INTST3            0x0040
    .DB4    0xffffffff                      ;   INTSR3                              0x0042
    BR      !!_r_dsadc_interrupt            ;   INTDSAD/INTSMP05/INTSMP15           0x0044
    .DB4    0xffffffff                      ;   INTTM04                             0x0046
    .DB4    0xffffffff                      ;   INTSMOTA0/INTTM05                   0x0048
    .DB4    0xffffffff                      ;   INTP6                               0x004A
    .DB4    0xffffffff                      ;   INTP7                               0x004C
    .DB4    0xffffffff                      ;   INTP12/INTRTCIC2                    0x004E
    .DB4    0xffffffff                      ;   INTP13/INTRTCIC1                    0x0050
    .DB4    0xffffffff                      ;   INTP14/INTRTCIC0                    0x0052
    .DB4    0xffffffff                      ;   INTSMOTB0/INTTM06                   0x0054
    .DB4    0xffffffff                      ;   INTSMOTA1/INTTM07                   0x0056
    .DB4    0xffffffff                      ;   INTIT00                             0x0058
    .DB4    0xffffffff                      ;   INTIT01                             0x005A
    .DB4    0xffffffff                      ;   INTSRE3                             0x005C
    BR      !!_r_mac32bit_interrupt_flow    ;   INTMACLOF/INTSMOTB1                 0x005E
    .DB4    0xffffffff                      ;   INTOSDC                             0x0060
    .DB4    0xffffffff                      ;   INTFL                               0x0062
    .DB4    0xffffffff                      ;   INTP8                               0x0064
    .DB4    0xffffffff                      ;   INTP9                               0x0066
    .DB4    0xffffffff                      ;   INTIT10                             0x0068
    .DB4    0xffffffff                      ;   INTIT11                             0x006A
    .DB4    0xffffffff                      ;   INTIT20/INTLVDVDD                   0x006C
    .DB4    0xffffffff                      ;   INTIT21/INTLVDVBAT                  0x006E
    .DB4    0xffffffff                      ;   INTIT30/INTLVDVRTC                  0x0070
    .DB4    0xffffffff                      ;   INTIT31/INTLVDEXLVD                 0x0072
    .DB4    0xffffffff                      ;   INTST4/INTSTMG1                     0x0074
    .DB4    0xffffffff                      ;   INTSR4/INTSRMG1                     0x0076
    .DB4    0xffffffff                      ;   INTSRE4/INTSREMG1                   0x0078
    .DB4    0xffffffff                      ;   INTDSADDEC/INTTRJ0                  0x007A
    .DB4    0xffffffff                      ;   INTTRJ1                             0x007C
    .DB4    0xffffffff                      ;   Software break                      0x007E
       